# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 21:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 19, 21, 52, 37, 638348)),
        ),
    ]
