# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 05:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20160320_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 20, 5, 16, 26, 657583)),
        ),
    ]
