# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 02:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20160320_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbpost',
            old_name='postobject',
            new_name='object',
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 25, 2, 6, 39, 240976)),
        ),
    ]
