# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-10 23:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20160326_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOTD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('day', models.DateField(default=datetime.datetime(2016, 9, 10, 23, 15, 15, 491322))),
                ('definition', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 10, 23, 15, 15, 488795)),
        ),
    ]
