# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-10 23:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20160910_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 10, 23, 17, 46, 423350)),
        ),
        migrations.AlterField(
            model_name='wotd',
            name='day',
            field=models.DateField(default=datetime.datetime(2016, 9, 10, 23, 17, 46, 425965)),
        ),
    ]
