# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-18 23:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20160917_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 18, 23, 3, 7, 475734)),
        ),
        migrations.AlterField(
            model_name='wotd',
            name='day',
            field=models.DateField(default=datetime.datetime(2016, 9, 18, 23, 3, 7, 477635)),
        ),
    ]
