# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 04:49
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20170806_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedmessage',
            name='attachment_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), blank=True, size=8),
        ),
        migrations.AlterField(
            model_name='loggedmessage',
            name='timestamp_logged',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 6, 4, 49, 10, 127948)),
        ),
        migrations.AlterField(
            model_name='wotd',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 8, 6, 4, 49, 10, 129889)),
        ),
    ]
