# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 04:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_auto_20170806_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedmessage',
            name='attachment_urls',
        ),
        migrations.AddField(
            model_name='loggedmessage',
            name='attachment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 6, 4, 55, 23, 640008)),
        ),
        migrations.AlterField(
            model_name='wotd',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 8, 6, 4, 55, 23, 642155)),
        ),
    ]
