# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_auto_20170806_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedmessage',
            name='api_id',
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 6, 18, 7, 22, 528859)),
        ),
        migrations.AlterField(
            model_name='wotd',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 8, 6, 18, 7, 22, 530892)),
        ),
    ]
